// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using core_website;

#nullable disable

namespace core_website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027161746_BackupData_2025_10_27")]
    partial class BackupData_2025_10_27
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanhMucSanPham", b =>
                {
                    b.Property<int>("DanhMucMaDM")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamMaSP")
                        .HasColumnType("int");

                    b.HasKey("DanhMucMaDM", "SanPhamMaSP");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("DanhMucSanPham");
                });

            modelBuilder.Entity("core_website.Areas.Api.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDM"));

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDM");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("core_website.Areas.Api.Models.PhanLoai", b =>
                {
                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("MaDM")
                        .HasColumnType("int");

                    b.HasKey("MaSP", "MaDM");

                    b.HasIndex("MaDM");

                    b.ToTable("PhanLoai", (string)null);
                });

            modelBuilder.Entity("core_website.Areas.Api.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("KhuyenMai")
                        .HasColumnType("Decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<string>("ThongSo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSP");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("DanhMucSanPham", b =>
                {
                    b.HasOne("core_website.Areas.Api.Models.DanhMuc", null)
                        .WithMany()
                        .HasForeignKey("DanhMucMaDM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("core_website.Areas.Api.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("SanPhamMaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core_website.Areas.Api.Models.PhanLoai", b =>
                {
                    b.HasOne("core_website.Areas.Api.Models.DanhMuc", "DanhMuc")
                        .WithMany("PhanLoai")
                        .HasForeignKey("MaDM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("core_website.Areas.Api.Models.SanPham", "SanPham")
                        .WithMany("PhanLoai")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("core_website.Areas.Api.Models.DanhMuc", b =>
                {
                    b.Navigation("PhanLoai");
                });

            modelBuilder.Entity("core_website.Areas.Api.Models.SanPham", b =>
                {
                    b.Navigation("PhanLoai");
                });
#pragma warning restore 612, 618
        }
    }
}
